### ISSUE TITLE
Error starting embedded DCGM engine

### ISSUE THREAD

**Issue by fabito** [triton-inference-server/model_analyzer#16]
I'm trying to run model-analyzer in kubernetes but it is failing  with the following error:

``` Error: Failed to initialize NVML                                                                                                                                                           
│ Unhandled exception. System.TypeInitializationException: The type initializer for 'Triton.MemoryAnalyzer.Metrics.GpuMetrics' threw an exception.                                           │
│  ---> System.InvalidOperationException: Error starting embedded DCGM engine. DCGM initialization error.                                                                                    │
│    at Triton.MemoryAnalyzer.Metrics.GpuMetrics..cctor()                                                                                                                                    │
│    --- End of inner exception stack trace ---                                                                                                                                              │
│    at Triton.MemoryAnalyzer.Metrics.GpuMetrics..ctor()                                                                                                                                     │
│    at Triton.MemoryAnalyzer.MetricsCollector..ctor(MetricsCollectorConfig config)                                                                                                          │
│    at Triton.MemoryAnalyzer.Program.<>c__DisplayClass7_0.<Main>b__2(K8sOptions options)                                                                                                    │
│    at CommandLine.ParserResultExtensions.MapResult[T1,T2,TResult](ParserResult`1 result, Func`2 parsedFunc1, Func`2 parsedFunc2, Func`2 notParsedFunc)                                     │
│    at Triton.MemoryAnalyzer.Program.Main(String[] args)                                                                                                                                    │
│ stream closed 
```
Has anyone seen it before ?

**Comment by KingsleyLiu-NV** [comment]
same error here
```bash
Error: Failed to initialize NVML
Unhandled exception. System.TypeInitializationException: The type initializer for 'Triton.MemoryAnalyzer.Metrics.GpuMetrics' threw an exception.
 ---> System.InvalidOperationException: Error starting embedded DCGM engine. DCGM initialization error.
   at Triton.MemoryAnalyzer.Metrics.GpuMetrics..cctor()
   --- End of inner exception stack trace ---
   at Triton.MemoryAnalyzer.Metrics.GpuMetrics..ctor()
   at Triton.MemoryAnalyzer.MetricsCollector..ctor(MetricsCollectorConfig config)
   at Triton.MemoryAnalyzer.Program.<>c__DisplayClass7_0.<Main>b__1(CLIOptions options)
   at CommandLine.ParserResultExtensions.MapResult[T1,T2,TResult](ParserResult`1 result, Func`2 parsedFunc1, Func`2 parsedFunc2, Func`2 notParsedFunc)
   at Triton.MemoryAnalyzer.Program.Main(String[] args)

```

**Comment by dyastremsky** [comment]
This looks like your system does not meet the [requirements for DCGM](https://docs.nvidia.com/datacenter/dcgm/latest/dcgm-user-guide/getting-started.html), which is used by the current version of Model Analyzer. Does your system meet the minimum standards for Model Analyzer?

Triton Memory Analyzer supports the following products and environments:

- All K80 and newer Tesla GPUs
- NVSwitch on DGX-2 and HGX-2
- All Maxwell and newer non-Tesla GPUs
- CUDA 7.5+ and NVIDIA Driver R384+

**Comment by fabito** [comment]
My environment is:

GKE 1.17.9-gke.1504

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.51.06    Driver Version: 450.51.06    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   59C    P0    29W /  70W |   8968MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```

What am I missing ?

**Comment by dyastremsky** [comment]
It looks like your system meets the requirements for DCGM. Could you try starting DCGM separately and report back whether it works standalone? https://docs.nvidia.com/datacenter/dcgm/latest/dcgm-user-guide/getting-started.html#installation

CC'ing @whoisj @igobypenn for awareness.

**Comment by fabito** [comment]
@dyastremsky , just noticed I'm using `20.09-py3`. According to the README:

>  Triton Memory Analyzer supports Triton Inference Server version 20.02-py3

Could that be the problem ?

**Comment by dyastremsky** [comment]
> @dyastremsky , just noticed I'm using `20.09-py3`. According to the README:
> 
> > Triton Memory Analyzer supports Triton Inference Server version 20.02-py3
> 
> Could that be the problem ?

I don't think so. The Helm chart would pull the right version of Triton. Based on this error, it's the DCGM package that is failing to start.

**Comment by KingsleyLiu-NV** [comment]
@dyastremsky DCGM works standlone:
```bash
kingsleyl@A41010:~/Downloads$ dcgmi discovery -l
1 GPU found.
+--------+----------------------------------------------------------------------+
| GPU ID | Device Information                                                   |
+--------+----------------------------------------------------------------------+
| 0      | Name: GeForce RTX 2080 Ti                                            |
|        | PCI Bus ID: 00000000:07:00.0                                         |
|        | Device UUID: GPU-23f41417-1d23-98c4-8792-bcdc51e0ec9f                |
+--------+----------------------------------------------------------------------+
0 NvSwitches found.
+-----------+
| Switch ID |
+-----------+
+-----------+
```
But the same error when trying to run the memory analyzer:
```bash
docker run -v /var/run/docker.sock:/var/run/docker.sock -v /home/kingsleyl/Projects/triton-inference-server/server/docs/examples/model_repository:/home/user/models -v /home/kingsleyl/Projects/triton-inference-server/server/docs/results:/results --net=host memory-analyzer:latest --batch 1,2 --concurrency 1,2 --model-names resnet50_netdef --triton-version 20.02-py3 --model-folder /home/user/models --export --export-path /results/
Error: Failed to initialize NVML
Unhandled exception. System.TypeInitializationException: The type initializer for 'Triton.MemoryAnalyzer.Metrics.GpuMetrics' threw an exception.
 ---> System.InvalidOperationException: Error starting embedded DCGM engine. DCGM initialization error.
   at Triton.MemoryAnalyzer.Metrics.GpuMetrics..cctor()
   --- End of inner exception stack trace ---
   at Triton.MemoryAnalyzer.Metrics.GpuMetrics..ctor()
   at Triton.MemoryAnalyzer.MetricsCollector..ctor(MetricsCollectorConfig config)
   at Triton.MemoryAnalyzer.Program.<>c__DisplayClass7_0.<Main>b__1(CLIOptions options)
   at CommandLine.ParserResultExtensions.MapResult[T1,T2,TResult](ParserResult`1 result, Func`2 parsedFunc1, Func`2 parsedFunc2, Func`2 notParsedFunc)
   at Triton.MemoryAnalyzer.Program.Main(String[] args)
```

**Comment by fabito** [comment]
I think I made some progress.
Before I was only requesting a GPU for the `triton` container:

```yaml
        image: nvcr.io/nvidia/tritonserver:20.09-py3
        name: triton
        resources:
          limits:
            cpu: "2"
            memory: 8192M
            nvidia.com/gpu: "1"
          requests:
            cpu: "1"
            memory: 4096M
```
After requesting another GPU for the `analyzer` container, that error is gone:

```yaml
        image: gcr.io/myproject/ml/nvidia/memory-analyzer:20.09-py3
        name: analyzer
        resources:
          limits:
            cpu: "2"
            memory: 8192M
            nvidia.com/gpu: "1"
          requests:
            cpu: "1"
            memory: 4096M
```
Is it a valid workaround ? Will the `analyzer` container  be able to check/poll the `triton` container GPU utilization ? 

Anyway, now I'm getting the error below:

```
analyzer Grpc.Core.RpcException: Status(StatusCode="Unimplemented", Detail="", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1603941283.856166700","description" 
 :"Error received from peer ipv4:127.0.0.1:8001","file":"/var/local/git/grpc/src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"","grpc_status":12}")                             
 analyzer    at Grpc.Core.Internal.AsyncCall`2.UnaryCall(TRequest msg)                                                                                                                        
 analyzer    at Grpc.Core.Calls.BlockingUnaryCall[TRequest,TResponse](CallInvocationDetails`2 call, TRequest req)                                                                             
 analyzer    at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)                                       
 analyzer    at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)                                    
 analyzer    at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, B 
 lockingUnaryCallContinuation`2 continuation)                                                                                                                                                 
 analyzer    at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)                     
 analyzer    at Triton.MemoryAnalyzer.Client.GRPCService.GRPCServiceClient.Status(StatusRequest request, CallOptions options)                                                                 
 analyzer    at Triton.MemoryAnalyzer.Client.GRPCService.GRPCServiceClient.Status(StatusRequest request, Metadata headers, Nullable`1 deadline, CancellationToken cancellationToken)          
 analyzer    at Triton.MemoryAnalyzer.Client.TritonGrpcClient.GetStatus(IPAddress ipAddress, Int32 port)                                                                                      
 analyzer    at Triton.MemoryAnalyzer.ModelAnalyzer.IsPortReady(TritonGrpcClient client)                                                                                                      
 analyzer    at Triton.MemoryAnalyzer.ModelAnalyzer.WaitUntilPortReady()                                                                                                                      
 analyzer    at Triton.MemoryAnalyzer.ModelAnalyzer.Run(Process clientProcess)                                                                                                                
 analyzer    at Triton.MemoryAnalyzer.ModelAnalyzer.RunK8s()                                                                                                                                  
 analyzer    at Triton.MemoryAnalyzer.Program.<>c__DisplayClass7_0.<Main>b__2(K8sOptions options)                                                                                             
 analyzer Server Only:                                                                                                                                                                        
 analyzer Model                         Batch               Concurrency         Throughput          Max Memory Util(%)  Max GPU Util(%)     Max BAR1(MB)        Max Framebuffer(MB)           
 analyzer Models:                                                                                                                                                                             
 analyzer Model                         Batch               Concurrency         Throughput          Max Memory Util(%)  Max GPU Util(%)     Max BAR1(MB)        Max Framebuffer(MB)           
```

**Comment by dyastremsky** [comment]
@fabito The exception is because you are calling an unsupported version of Triton. The APIs changed in between versions, so you need to use 20.02-py3. Apologies for the confusion earlier - I thought you meant you had a different version on your computer.

The results of that workaround seem like they would be unpredictable. Are you putting both containers into the same pod? You should be able to use the Helm chart. The containers need to be in the same pod to share a GPU and communicate.

@igobypenn Would you be able to take a look, or do you know someone who may be familiar with DCGM to try the Docker command? I don't currently have access to a DCGM-compatible GPU to test why it wouldn't be working.

**Comment by fabito** [comment]
@dyastremsky , yes both containers are in the same job/pod, my manifest is based in the helm chart from this repo with very few modifications.

I don't understand how the shared GPU will work. AFAIK that's not possible yet: https://github.com/kubernetes/kubernetes/issues/52757

**Comment by dyastremsky** [comment]
@fabito Ignore my earlier comment, you're right. Analyzer surveys the memory usage on the system, not a specific GPU. I suppose it would work fine, but I don't know why allocating a GPU would make a difference unless there's an underlying issue with the configuration. Feel free to test it out.

They should be in the same pod, not container. Are you sure none of the modifications you made were critical? For example, securityContext should be set to privileged: true for analyzer and sharePorcessNamespace should be set to true for the pod.

**Comment by whoisj** [comment]
@fabito are you running the Model Analyzer inside the provided container? If not, which operating system are trying this with?

DCGM is a native binary, meaning it was compiled for a specific environment. In this case it was compiled for Ubuntu 18.04. Use of another operating system can lead to dynamic linking issues which will surface as type-initializer exceptions.

**Comment by whoisj** [comment]
@KingsleyLiu-NV the error is happening [here](https://github.com/triton-inference-server/model_analyzer/blob/main/src/Metrics/GpuMetrics.cs#L65), meaning that `dcmgInit()`  returned `-7`.

Not having access to the DCGM code, I don't know what `-7` means besides "sorry, that didn't go as planned" - any chance you can help shed some light on the situation?

**Comment by whoisj** [comment]
As for the second reported error, the GRPC subsystem is reporting that the method in question hasn't been implemented.

Memory Analyzer is trying to call Triton's GetStatus RPC, and it appears that Triton is answering the connection and immediately hanging up with a
```
Status(StatusCode="Unimplemented", Detail="", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1603941283.856166700","description" 
 :"Error received from peer ipv4:127.0.0.1:8001","file":"/var/local/git/grpc/src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"","grpc_status":12}")
```

**Comment by fabito** [comment]
> @fabito The exception is because you are calling an unsupported version of Triton. The APIs changed in between versions, so you need to use 20.02-py3. Apologies for the confusion earlier - I thought you meant you had a different version on your computer.

I can try `20.02-py3` sometime later. But I think it is kind of pointless since we are running `20.09-py3` in production.

Should we create another issue to add `20.09-py3` support ?

**Comment by dyastremsky** [comment]
@fabito Not yet. The Triton team is integrating this tool into the Triton universe, including a complete rewrite in C++. I briefly skimmed the code in [that branch](https://github.com/triton-inference-server/model_analyzer/tree/main-dev/). My assumption is that it will support more current versions of Triton and better integrate into the experience you are accustomed to with Triton.

I'm not involved in that project, so I do not know the timeline. @deadeyegoodwin and @dzier would be better contacts for that. In the meantime, hopefully this version of Triton Memory Analyzer can provide you with approximate memory metrics.

**Comment by whoisj** [comment]
Took some time, but I got a suggestion on how to better debug this issue. If we set
```
__DCGM_DBG_FILE=dcgm.log
__DCMG_DBG_LVL=WARNING
```
in the environment, prior to initializing libdcgm, then it'll write logs to `/var/log/dcgm.log` which we can use to better debug the issue.

It's probably also worth our time to check if a `/var/log/dcgm.log` file exists as well.

**Comment by dzier** [comment]
We have just pushed out the new rewrite in Python to the `main` branch. Please try the newer version and see if the issues still persist. Note we will officially releasing v1.0.0 of ModelAnalyzer in the 20.12 release of Triton SDK, which will be sometime in December.

**Comment by Tabrizian** [comment]
Closing the issue for now. Feel free to reopen if the issue persists.
