### ISSUE TITLE
 question about --triton-launch-mode=docker   

### ISSUE THREAD

**Issue by BobDLA** [triton-inference-server/model_analyzer#607]
The model requires for several other pip dependency not installed in 
nvcr.io/nvidia/tritonserver:23.01-py3

So, I update the docker image by a docker file like 

from nvcr.io/nvidia/tritonserver:23.01-py3
RUN pip install opencv-contrib-python-headless  onnxruntime-gpu 

And create a tag like triton_onnx:0.1

But when I start the model_analyzer, I got error

07:31:58 [Model Analyzer] Initializing GPUDevice handles
07:31:59 [Model Analyzer] Using GPU 0 NVIDIA GeForce RTX 2060 with UUID GPU-f7572576-2bd0-ee4f-cd17-0a7a8ec6da5b
07:31:59 [Model Analyzer] Starting a Triton Server using docker
07:31:59 [Model Analyzer] Pulling docker image triton_onnx:0.1
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.40/images/create?tag=0.1&fromImage=triton_onnx

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/model-analyzer", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/model_analyzer/entrypoint.py", line 256, in main
    client, server = get_triton_handles(config, gpus)
  File "/usr/local/lib/python3.8/dist-packages/model_analyzer/entrypoint.py", line 130, in get_triton_handles
    server = TritonServerFactory.get_server_handle(config, gpus)
  File "/usr/local/lib/python3.8/dist-packages/model_analyzer/triton/server/server_factory.py", line 129, in get_server_handle
    server = TritonServerFactory._get_docker_server_handle(
  File "/usr/local/lib/python3.8/dist-packages/model_analyzer/triton/server/server_factory.py", line 216, in _get_docker_server_handle
    server = TritonServerFactory.create_server_docker(
  File "/usr/local/lib/python3.8/dist-packages/model_analyzer/triton/server/server_factory.py", line 69, in create_server_docker
    return TritonServerDocker(image=image,
  File "/usr/local/lib/python3.8/dist-packages/model_analyzer/triton/server/server_docker.py", line 72, in __init__
    self._docker_client.images.pull(self._tritonserver_image)
  File "/usr/local/lib/python3.8/dist-packages/docker/models/images.py", line 465, in pull
    pull_log = self.client.api.pull(
  File "/usr/local/lib/python3.8/dist-packages/docker/api/image.py", line 429, in pull
    self._raise_for_status(response)
  File "/usr/local/lib/python3.8/dist-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
  File "/usr/local/lib/python3.8/dist-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.ImageNotFound: 404 Client Error for http+docker://localhost/v1.40/images/create?tag=0.1&fromImage=triton_onnx: Not Found ("pull access denied for triton_onnx, repository does not exist or may require 'docker login': denied: requested access to the resource is denied")

Seems, the model_anlyzer pull the image from server which not exists and stop to run.
How to fix this issue?

Thanks

**Comment by tgerdesnv** [comment]
The code incorrectly assumed that the docker image would be remote. I have put up a PR that should support locally created/tagged docker images as well.

**Comment by BobDLA** [comment]
> The code incorrectly assumed that the docker image would be remote. I have put up a PR that should support locally created/tagged docker images as well.

Thanks for your quick aciton.

**Comment by niuzheng168** [comment]
does the issue resolved? I got similar issue and just tried 23.03, the issue still there

**Comment by tgerdesnv** [comment]
@niuzheng168 yes this issue was resolved. If you are seeing a problem please open up a new issue.
