### ISSUE TITLE
failed to poll model : model not found in any model repository

### ISSUE THREAD

**Issue by adithya-Avataar** [triton-inference-server/model_analyzer#786]
Hi
I have a custom model of mine, which I am able to run successfully using tritonserver. It is a BLS kind of model. The main model is named `pipe`.  
Docker command used to start the client/MA is as follows:
`sudo docker run -it --gpus all -v /var/run/docker.sock:/var/run/docker.sock -v /home/ubuntu/tensor_rt/triton/client:/workspace/runs -v /home/ubuntu/tensor_rt/triton/output_models:/workspace/output_models -v /home/ubuntu/tensor_rt/triton/sd_test:/models/ --net host --name triton_client nvcr.io/nvidia/tritonserver:23.10-py3-sdk`

Structure of my  `/home/ubuntu/tensor_rt/triton/sd_test` (on host)
|sd_test
|----aux_models
|--------meta
|----models
|--------model1
|--------model2
|--------model3
|--------model4
|--------pipe

Command used to start the model analzyer inside the container:
`model-analyzer -v profile --model-repository /models/models/ --profile-models pipe --triton-launch-mode=docker --output-model-repository-path output_models/trial_1 --export-path runs/profile_results --override-output-model-repository --triton-docker-image triton_image --triton-output-path triton_log.txt --triton-docker-mounts "/models:/models:rw,/workspace/runs/profile_results:/profile_results:rw"`

Output of the MA:

```
07:46:50 [Model Analyzer] DEBUG: 
{'always_report_gpu_metrics': False,
 'batch_sizes': [1],
 'bls_composing_models': [],
 'checkpoint_directory': '/workspace/checkpoints',
 'client_max_retries': 50,
 'client_protocol': 'grpc',
 'collect_cpu_metrics': False,
 'concurrency': [],
 'config_file': None,
 'constraints': {},
 'cpu_only_composing_models': [],
 'duration_seconds': 3,
 'early_exit_enable': False,
 'export_path': 'runs/profile_results',
 'filename_model_gpu': 'metrics-model-gpu.csv',
 'filename_model_inference': 'metrics-model-inference.csv',
 'filename_server_only': 'metrics-server-only.csv',
 'gpu_output_fields': ['model_name',
                       'gpu_uuid',
                       'batch_size',
                       'concurrency',
                       'model_config_path',
                       'instance_group',
                       'satisfies_constraints',
                       'gpu_used_memory',
                       'gpu_utilization',
                       'gpu_power_usage'],
 'gpus': ['all'],
 'inference_output_fields': ['model_name',
                             'batch_size',
                             'concurrency',
                             'model_config_path',
                             'instance_group',
                             'max_batch_size',
                             'satisfies_constraints',
                             'perf_throughput',
                             'perf_latency_p99'],
 'latency_budget': None,
 'min_throughput': None,
 'model_repository': '/models/models/',
 'monitoring_interval': 1.0,
 'num_configs_per_model': 3,
 'num_top_model_configs': 0,
 'objectives': {'perf_throughput': 10},
 'output_model_repository_path': 'output_models/trial_1',
 'override_output_model_repository': True,
 'perf_analyzer_cpu_util': 1280.0,
 'perf_analyzer_flags': {},
 'perf_analyzer_max_auto_adjusts': 10,
 'perf_analyzer_path': 'perf_analyzer',
 'perf_analyzer_timeout': 600,
 'perf_output': False,
 'perf_output_path': None,
 'plots': [{'name': 'throughput_v_latency', 'title': 'Throughput vs. Latency', 'x_axis': 'perf_latency_p99', 'y_axis': 'perf_throughput', 'monotonic': True},
           {'name': 'gpu_mem_v_latency', 'title': 'GPU Memory vs. Latency', 'x_axis': 'perf_latency_p99', 'y_axis': 'gpu_used_memory', 'monotonic': False}],
 'profile_models': [{'model_name': 'pipe', 'cpu_only': False, 'objectives': {'perf_throughput': 10}, 'parameters': {'batch_sizes': [1], 'concurrency': [], 'request_rate': []}, 'weighting': 1}],
 'reload_model_disable': False,
 'request_rate': [],
 'request_rate_search_enable': False,
 'run_config_profile_models_concurrently_enable': False,
 'run_config_search_disable': False,
 'run_config_search_max_binary_search_steps': 5,
 'run_config_search_max_concurrency': 1024,
 'run_config_search_max_instance_count': 5,
 'run_config_search_max_model_batch_size': 128,
 'run_config_search_max_request_rate': 8192,
 'run_config_search_min_concurrency': 1,
 'run_config_search_min_instance_count': 1,
 'run_config_search_min_model_batch_size': 1,
 'run_config_search_min_request_rate': 16,
 'run_config_search_mode': 'brute',
 'server_output_fields': ['model_name',
                          'gpu_uuid',
                          'gpu_used_memory',
                          'gpu_utilization',
                          'gpu_power_usage'],
 'skip_detailed_reports': False,
 'skip_summary_reports': False,
 'triton_docker_args': {},
 'triton_docker_image': 'triton_image',
 'triton_docker_labels': {},
 'triton_docker_mounts': ['/models:/models:rw',
                          '/workspace/runs/profile_results:/profile_results:rw'],
 'triton_docker_shm_size': None,
 'triton_grpc_endpoint': 'localhost:8001',
 'triton_http_endpoint': 'localhost:8000',
 'triton_install_path': '/opt/tritonserver',
 'triton_launch_mode': 'docker',
 'triton_metrics_url': 'http://localhost:8002/metrics',
 'triton_output_path': 'triton_log.txt',
 'triton_server_environment': {},
 'triton_server_flags': {},
 'triton_server_path': 'tritonserver',
 'weighting': None}
07:46:50 [Model Analyzer] Initializing GPUDevice handles
07:46:51 [Model Analyzer] Using GPU 0 NVIDIA A10G with UUID GPU-53c85dc1-936c-a3e4-765c-60657311f1d0
07:46:51 [Model Analyzer] WARNING: Overriding the output model repo path "output_models/trial_1"
07:46:51 [Model Analyzer] Starting a Triton Server using docker
07:46:51 [Model Analyzer] Loaded checkpoint from file /workspace/checkpoints/1.ckpt
07:46:51 [Model Analyzer] GPU devices match checkpoint - skipping server metric acquisition
07:46:51 [Model Analyzer] 
07:46:51 [Model Analyzer] Starting automatic brute search
07:46:51 [Model Analyzer] 
07:46:51 [Model Analyzer] Creating model config: pipe_config_default
07:46:51 [Model Analyzer] 
07:47:00 [Model Analyzer] DEBUG: Triton Server started.
07:47:08 [Model Analyzer] Model pipe_config_default load failed: [StatusCode.INTERNAL] failed to load 'pipe', failed to poll from model repository
07:47:12 [Model Analyzer] DEBUG: Stopped Triton Server.
07:47:12 [Model Analyzer] Saved checkpoint to /workspace/checkpoints/2.ckpt
07:47:12 [Model Analyzer] Creating model config: pipe_config_0
07:47:12 [Model Analyzer]   Setting instance_group to [{'count': 1, 'kind': 'KIND_GPU'}]
07:47:12 [Model Analyzer]   Setting max_batch_size to 1
07:47:12 [Model Analyzer]   Enabling dynamic_batching
07:47:12 [Model Analyzer] 
07:47:13 [Model Analyzer] DEBUG: Triton Server started.
07:47:18 [Model Analyzer] Model pipe_config_0 load failed: [StatusCode.INTERNAL] failed to load 'pipe', failed to poll from model repository
07:47:22 [Model Analyzer] DEBUG: Stopped Triton Server.
07:47:22 [Model Analyzer] No changes made to analyzer data, no checkpoint saved.
Traceback (most recent call last):
  File "/usr/local/bin/model-analyzer", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/model_analyzer/entrypoint.py", line 278, in main
    analyzer.profile(
  File "/usr/local/lib/python3.10/dist-packages/model_analyzer/analyzer.py", line 124, in profile
    self._profile_models()
  File "/usr/local/lib/python3.10/dist-packages/model_analyzer/analyzer.py", line 242, in _profile_models
    self._model_manager.run_models(models=[model])
  File "/usr/local/lib/python3.10/dist-packages/model_analyzer/model_manager.py", line 145, in run_models
    self._stop_ma_if_no_valid_measurement_threshold_reached()
  File "/usr/local/lib/python3.10/dist-packages/model_analyzer/model_manager.py", line 239, in _stop_ma_if_no_valid_measurement_threshold_reached
    raise TritonModelAnalyzerException(
model_analyzer.model_analyzer_exceptions.TritonModelAnalyzerException: The first 2 attempts to acquire measurements have failed. Please examine the Tritonserver/PA error logs to determine what has gone wrong.
```


Output of the tritonserver log in triton_log.txt

> =============================
== Triton Inference Server ==
=============================

```
NVIDIA Release 23.10 (build 72127154)
Triton Server Version 2.39.0

Copyright (c) 2018-2023, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

WARNING: CUDA Minor Version Compatibility mode ENABLED.
  Using driver version 530.30.02 which has support for CUDA 12.1.  This container
  was built with CUDA 12.2 and will be run in Minor Version Compatibility mode.
  CUDA Forward Compatibility is preferred over Minor Version Compatibility for use
  with this container but was unavailable:
  [[System has unsupported display driver / cuda driver combination (CUDA_ERROR_SYSTEM_DRIVER_MISMATCH) cuInit()=803]]
  See https://docs.nvidia.com/deploy/cuda-compatibility/ for details.

Warning: '--strict-model-config' has been deprecated! Please use '--disable-auto-complete-config' instead.
I1107 07:33:56.080411 7 pinned_memory_manager.cc:241] Pinned memory pool is created at '0x7f8a18000000' with size 268435456
I1107 07:33:56.083827 7 cuda_memory_manager.cc:107] CUDA memory pool is created on device 0 with size 67108864
I1107 07:33:56.087180 7 server.cc:592] 
+------------------+------+
| Repository Agent | Path |
+------------------+------+
+------------------+------+

I1107 07:33:56.087203 7 server.cc:619] 
+---------+------+--------+
| Backend | Path | Config |
+---------+------+--------+
+---------+------+--------+

I1107 07:33:56.087212 7 server.cc:662] 
+-------+---------+--------+
| Model | Version | Status |
+-------+---------+--------+
+-------+---------+--------+

I1107 07:33:56.126179 7 metrics.cc:817] Collecting metrics for GPU 0: NVIDIA A10G
I1107 07:33:56.126464 7 metrics.cc:710] Collecting CPU metrics
I1107 07:33:56.126625 7 tritonserver.cc:2458] 
+----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Option                           | Value                                                                                                                                                                                                           |
+----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| server_id                        | triton                                                                                                                                                                                                          |
| server_version                   | 2.39.0                                                                                                                                                                                                          |
| server_extensions                | classification sequence model_repository model_repository(unload_dependents) schedule_policy model_configuration system_shared_memory cuda_shared_memory binary_tensor_data parameters statistics trace logging |
| model_repository_path[0]         | /models/models                                                                                                                                                                                                  |
| model_control_mode               | MODE_EXPLICIT                                                                                                                                                                                                   |
| strict_model_config              | 0                                                                                                                                                                                                               |
| rate_limit                       | OFF                                                                                                                                                                                                             |
| pinned_memory_pool_byte_size     | 268435456                                                                                                                                                                                                       |
| cuda_memory_pool_byte_size{0}    | 67108864                                                                                                                                                                                                        |
| min_supported_compute_capability | 6.0                                                                                                                                                                                                             |
| strict_readiness                 | 1                                                                                                                                                                                                               |
| exit_timeout                     | 30                                                                                                                                                                                                              |
| cache_enabled                    | 0                                                                                                                                                                                                               |
+----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

I1107 07:33:56.127801 7 grpc_server.cc:2513] Started GRPCInferenceService at 0.0.0.0:8001
I1107 07:33:56.128028 7 http_server.cc:4497] Started HTTPService at 0.0.0.0:8000
I1107 07:33:56.168973 7 http_server.cc:270] Started Metrics Service at 0.0.0.0:8002
E1107 07:34:03.823179 7 model_repository_manager.cc:1265] failed to poll model 'pipe': model not found in any model repository.

=============================
== Triton Inference Server ==
=============================

NVIDIA Release 23.10 (build 72127154)
Triton Server Version 2.39.0

Copyright (c) 2018-2023, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

WARNING: CUDA Minor Version Compatibility mode ENABLED.
  Using driver version 530.30.02 which has support for CUDA 12.1.  This container
  was built with CUDA 12.2 and will be run in Minor Version Compatibility mode.
  CUDA Forward Compatibility is preferred over Minor Version Compatibility for use
  with this container but was unavailable:
  [[System has unsupported display driver / cuda driver combination (CUDA_ERROR_SYSTEM_DRIVER_MISMATCH) cuInit()=803]]
  See https://docs.nvidia.com/deploy/cuda-compatibility/ for details.

Warning: '--strict-model-config' has been deprecated! Please use '--disable-auto-complete-config' instead.
I1107 07:34:09.004050 7 pinned_memory_manager.cc:241] Pinned memory pool is created at '0x7f31d0000000' with size 268435456
I1107 07:34:09.007313 7 cuda_memory_manager.cc:107] CUDA memory pool is created on device 0 with size 67108864
I1107 07:34:09.010657 7 server.cc:592] 
+------------------+------+
| Repository Agent | Path |
+------------------+------+
+------------------+------+

I1107 07:34:09.010679 7 server.cc:619] 
+---------+------+--------+
| Backend | Path | Config |
+---------+------+--------+
+---------+------+--------+

I1107 07:34:09.010688 7 server.cc:662] 
+-------+---------+--------+
| Model | Version | Status |
+-------+---------+--------+
+-------+---------+--------+

I1107 07:34:09.049361 7 metrics.cc:817] Collecting metrics for GPU 0: NVIDIA A10G
I1107 07:34:09.049666 7 metrics.cc:710] Collecting CPU metrics
I1107 07:34:09.049846 7 tritonserver.cc:2458] 
+----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Option                           | Value                                                                                                                                                                                                           |
+----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| server_id                        | triton                                                                                                                                                                                                          |
| server_version                   | 2.39.0                                                                                                                                                                                                          |
| server_extensions                | classification sequence model_repository model_repository(unload_dependents) schedule_policy model_configuration system_shared_memory cuda_shared_memory binary_tensor_data parameters statistics trace logging |
| model_repository_path[0]         | /models/models                                                                                                                                                                                                  |
| model_control_mode               | MODE_EXPLICIT                                                                                                                                                                                                   |
| strict_model_config              | 0                                                                                                                                                                                                               |
| rate_limit                       | OFF                                                                                                                                                                                                             |
| pinned_memory_pool_byte_size     | 268435456                                                                                                                                                                                                       |
| cuda_memory_pool_byte_size{0}    | 67108864                                                                                                                                                                                                        |
| min_supported_compute_capability | 6.0                                                                                                                                                                                                             |
| strict_readiness                 | 1                                                                                                                                                                                                               |
| exit_timeout                     | 30                                                                                                                                                                                                              |
| cache_enabled                    | 0                                                                                                                                                                                                               |
+----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

I1107 07:34:09.051480 7 grpc_server.cc:2513] Started GRPCInferenceService at 0.0.0.0:8001
I1107 07:34:09.051715 7 http_server.cc:4497] Started HTTPService at 0.0.0.0:8000
I1107 07:34:09.092854 7 http_server.cc:270] Started Metrics Service at 0.0.0.0:8002
E1107 07:34:13.742246 7 model_repository_manager.cc:1265] failed to poll model 'pipe': model not found in any model repository.

=============================
== Triton Inference Server ==
=============================

NVIDIA Release 23.10 (build 72127154)
Triton Server Version 2.39.0

Copyright (c) 2018-2023, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

WARNING: CUDA Minor Version Compatibility mode ENABLED.
  Using driver version 530.30.02 which has support for CUDA 12.1.  This container
  was built with CUDA 12.2 and will be run in Minor Version Compatibility mode.
  CUDA Forward Compatibility is preferred over Minor Version Compatibility for use
  with this container but was unavailable:
  [[System has unsupported display driver / cuda driver combination (CUDA_ERROR_SYSTEM_DRIVER_MISMATCH) cuInit()=803]]
  See https://docs.nvidia.com/deploy/cuda-compatibility/ for details.

Warning: '--strict-model-config' has been deprecated! Please use '--disable-auto-complete-config' instead.
I1107 07:47:00.596353 7 pinned_memory_manager.cc:241] Pinned memory pool is created at '0x7faa78000000' with size 268435456
I1107 07:47:00.599650 7 cuda_memory_manager.cc:107] CUDA memory pool is created on device 0 with size 67108864
I1107 07:47:00.603063 7 server.cc:592] 
+------------------+------+
| Repository Agent | Path |
+------------------+------+
+------------------+------+

I1107 07:47:00.603086 7 server.cc:619] 
+---------+------+--------+
| Backend | Path | Config |
+---------+------+--------+
+---------+------+--------+

I1107 07:47:00.603095 7 server.cc:662] 
+-------+---------+--------+
| Model | Version | Status |
+-------+---------+--------+
+-------+---------+--------+

I1107 07:47:00.641803 7 metrics.cc:817] Collecting metrics for GPU 0: NVIDIA A10G
I1107 07:47:00.642091 7 metrics.cc:710] Collecting CPU metrics
I1107 07:47:00.642261 7 tritonserver.cc:2458] 
+----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Option                           | Value                                                                                                                                                                                                           |
+----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| server_id                        | triton                                                                                                                                                                                                          |
| server_version                   | 2.39.0                                                                                                                                                                                                          |
| server_extensions                | classification sequence model_repository model_repository(unload_dependents) schedule_policy model_configuration system_shared_memory cuda_shared_memory binary_tensor_data parameters statistics trace logging |
| model_repository_path[0]         | /models/models                                                                                                                                                                                                  |
| model_control_mode               | MODE_EXPLICIT                                                                                                                                                                                                   |
| strict_model_config              | 0                                                                                                                                                                                                               |
| rate_limit                       | OFF                                                                                                                                                                                                             |
| pinned_memory_pool_byte_size     | 268435456                                                                                                                                                                                                       |
| cuda_memory_pool_byte_size{0}    | 67108864                                                                                                                                                                                                        |
| min_supported_compute_capability | 6.0                                                                                                                                                                                                             |
| strict_readiness                 | 1                                                                                                                                                                                                               |
| exit_timeout                     | 30                                                                                                                                                                                                              |
| cache_enabled                    | 0                                                                                                                                                                                                               |
+----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

I1107 07:47:00.643902 7 grpc_server.cc:2513] Started GRPCInferenceService at 0.0.0.0:8001
I1107 07:47:00.644138 7 http_server.cc:4497] Started HTTPService at 0.0.0.0:8000
I1107 07:47:00.685100 7 http_server.cc:270] Started Metrics Service at 0.0.0.0:8002
E1107 07:47:08.340650 7 model_repository_manager.cc:1265] failed to poll model 'pipe': model not found in any model repository.

=============================
== Triton Inference Server ==
=============================

NVIDIA Release 23.10 (build 72127154)
Triton Server Version 2.39.0

Copyright (c) 2018-2023, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

WARNING: CUDA Minor Version Compatibility mode ENABLED.
  Using driver version 530.30.02 which has support for CUDA 12.1.  This container
  was built with CUDA 12.2 and will be run in Minor Version Compatibility mode.
  CUDA Forward Compatibility is preferred over Minor Version Compatibility for use
  with this container but was unavailable:
  [[System has unsupported display driver / cuda driver combination (CUDA_ERROR_SYSTEM_DRIVER_MISMATCH) cuInit()=803]]
  See https://docs.nvidia.com/deploy/cuda-compatibility/ for details.

Warning: '--strict-model-config' has been deprecated! Please use '--disable-auto-complete-config' instead.
I1107 07:47:13.523220 7 pinned_memory_manager.cc:241] Pinned memory pool is created at '0x7f85f0000000' with size 268435456
I1107 07:47:13.526703 7 cuda_memory_manager.cc:107] CUDA memory pool is created on device 0 with size 67108864
I1107 07:47:13.530155 7 server.cc:592] 
+------------------+------+
| Repository Agent | Path |
+------------------+------+
+------------------+------+

I1107 07:47:13.530177 7 server.cc:619] 
+---------+------+--------+
| Backend | Path | Config |
+---------+------+--------+
+---------+------+--------+

I1107 07:47:13.530186 7 server.cc:662] 
+-------+---------+--------+
| Model | Version | Status |
+-------+---------+--------+
+-------+---------+--------+

I1107 07:47:13.568680 7 metrics.cc:817] Collecting metrics for GPU 0: NVIDIA A10G
I1107 07:47:13.568988 7 metrics.cc:710] Collecting CPU metrics
I1107 07:47:13.569186 7 tritonserver.cc:2458] 
+----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Option                           | Value                                                                                                                                                                                                           |
+----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| server_id                        | triton                                                                                                                                                                                                          |
| server_version                   | 2.39.0                                                                                                                                                                                                          |
| server_extensions                | classification sequence model_repository model_repository(unload_dependents) schedule_policy model_configuration system_shared_memory cuda_shared_memory binary_tensor_data parameters statistics trace logging |
| model_repository_path[0]         | /models/models                                                                                                                                                                                                  |
| model_control_mode               | MODE_EXPLICIT                                                                                                                                                                                                   |
| strict_model_config              | 0                                                                                                                                                                                                               |
| rate_limit                       | OFF                                                                                                                                                                                                             |
| pinned_memory_pool_byte_size     | 268435456                                                                                                                                                                                                       |
| cuda_memory_pool_byte_size{0}    | 67108864                                                                                                                                                                                                        |
| min_supported_compute_capability | 6.0                                                                                                                                                                                                             |
| strict_readiness                 | 1                                                                                                                                                                                                               |
| exit_timeout                     | 30                                                                                                                                                                                                              |
| cache_enabled                    | 0                                                                                                                                                                                                               |
+----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

I1107 07:47:13.570460 7 grpc_server.cc:2513] Started GRPCInferenceService at 0.0.0.0:8001
I1107 07:47:13.570671 7 http_server.cc:4497] Started HTTPService at 0.0.0.0:8000
I1107 07:47:13.611722 7 http_server.cc:270] Started Metrics Service at 0.0.0.0:8002
E1107 07:47:18.258678 7 model_repository_manager.cc:1265] failed to poll model 'pipe': model not found in any model repository.

```
I think the docker volume mounts are not happening inside the container launched by the MA. Not very sure of what is happening in this.

**Comment by nv-braf** [comment]
The issue is that the absolute path to the model and output model repository are not identical, which is required when running in docker mode. See [our installation documentation]( https://github.com/triton-inference-server/model_analyzer/blob/main/docs/install.md) for further details.

**Comment by adithya-Avataar** [comment]
I am having some trouble understanding exactly which paths and volumes need to be mounted. 

Trying to follow your advice I have tried these commands:

Starting the model analyzer container with:

`sudo docker run -it --gpus all -v /var/run/docker.sock:/var/run/docker.sock -v /home/ubuntu/tensor_rt/triton/client:/workspace/runs -v /home/ubuntu/tensor_rt/triton/output_models:/home/ubuntu/tensor_rt/triton/output_models -v /home/ubuntu/tensor_rt/triton/sd_test:/home/ubuntu/tensor_rt/triton/sd_test/ --net host --name triton_client nvcr.io/nvidia/tritonserver:23.10-py3-sdk`

Running the analyzer inside the container:

`model-analyzer profile     --model-repository /home/ubuntu/tensor_rt/triton/sd_test/models     --profile-models pipe --triton-launch-mode=docker     --output-model-repository-path /home/ubuntu/tensor_rt/triton/output_models/trial_1     --export-path profile_results --override-output-model-repository --triton-docker-image triton_image --triton-output-path triton_log.txt`

I have tried to keep the paths the same. But I still get the same error as before. The MA is able to start the triton server, but it is unable to find the models and their paths.

When a sibling container container is launched by MA, which volumes and from where do they get mounted?

**Comment by nv-braf** [comment]
I'm not sure. Can you try launching in local or remote mode and see if that solves your issue?

**Comment by adithya-Avataar** [comment]
Hi.. I think the issue was that this was a bls model and it was not loading the underlying models required. I changed a few things and made it an ensemble model and it works fine now.

Also can I not perform multi model concurrent analyzing when for an ensemble model?

**Comment by tgerdesnv** [comment]
That is correct. Model Analyzer does not currently support multi-model concurrent analysis with one or more ensemble models.

**Comment by adithya-Avataar** [comment]
Closing this issue
